package sprite

import "image"

// 8-direction character sprite support.
// 5 directions (south/north/east/south-east/north-east) are generated by AI,
// the remaining 3 directions (west/south-west/north-west) are made by horizontal mirroring.

// DirectionInfo is the direction metadata exposed to the frontend.
type DirectionInfo struct {
	Key      string `json:"key"`      // "south", "north-east", etc.
	Label    string `json:"label"`    // display name
	Short    string `json:"short"`    // grid abbreviation (S, NE, etc.)
	MirrorOf string `json:"mirrorOf"` // mirror source direction (empty means AI-generated)
	Row      int    `json:"row"`      // 3x3 grid row (0-2)
	Col      int    `json:"col"`      // 3x3 grid column (0-2)
}

// Directions is the full list of 8 directions (3x3 grid order).
var Directions = []DirectionInfo{
	{Key: "north-west", Label: "¾ Back-L", Short: "NW", MirrorOf: "north-east", Row: 0, Col: 0},
	{Key: "north", Label: "Back", Short: "N", Row: 0, Col: 1},
	{Key: "north-east", Label: "¾ Back-R", Short: "NE", Row: 0, Col: 2},
	{Key: "west", Label: "Left", Short: "W", MirrorOf: "east", Row: 1, Col: 0},
	{Key: "east", Label: "Right", Short: "E", Row: 1, Col: 2},
	{Key: "south-west", Label: "¾ Front-L", Short: "SW", MirrorOf: "south-east", Row: 2, Col: 0},
	{Key: "south", Label: "Front", Short: "S", Row: 2, Col: 1},
	{Key: "south-east", Label: "¾ Front-R", Short: "SE", Row: 2, Col: 2},
}

// GeneratedDirections is the order in which directions are generated by AI (south is first since it is the front reference).
var GeneratedDirections = []string{"south", "east", "north", "south-east", "north-east"}

// ListDirections returns the list of direction metadata.
func ListDirections() []DirectionInfo {
	return Directions
}

// DirectionByKey returns the direction info matching the key.
func DirectionByKey(key string) (DirectionInfo, bool) {
	for _, d := range Directions {
		if d.Key == key {
			return d, true
		}
	}
	return DirectionInfo{}, false
}

// IsBackFacing reports whether the key is a back-facing direction where the face is not visible.
// (These directions are prone to false positives in the color-histogram identity check against the front base image.)
func IsBackFacing(key string) bool {
	switch key {
	case "north", "north-east", "north-west":
		return true
	}
	return false
}

// facingDesc holds the camera/body description for each direction.
type facingDesc struct {
	view       string // view type summary
	camera     string // camera angle
	body       string // body orientation
	visibility string // visible body parts
}

var facingDescs = map[string]facingDesc{
	"south": {
		view:       "front view",
		camera:     "camera directly in front, at eye level",
		body:       "the character faces the viewer directly",
		visibility: "full face visible (eyes and mouth, minimal nose detail); both arms and both legs fully visible, symmetric",
	},
	"north": {
		view:       "back view",
		camera:     "camera positioned directly behind the character",
		body:       "the character faces away from the viewer",
		visibility: "face completely hidden, only the back of the head and hair visible; back of the outfit, both arms and legs seen from behind",
	},
	"east": {
		view:       "right-side profile view",
		camera:     "camera at the character's right side, perpendicular to the body; strictly 2D profile, no perspective rotation",
		body:       "the character faces and moves toward the RIGHT edge of the canvas",
		visibility: "right profile of the face only (one eye, one ear); right arm and right leg prominent, left limbs fully hidden behind the body; never show parts of the left side",
	},
	"south-east": {
		view:       "three-quarter front-right view",
		camera:     "camera at front-right, rotated about 45 degrees from straight ahead",
		body:       "the character is turned about 45 degrees to the right, mostly facing the viewer",
		visibility: "3/4 face with both eyes visible, right side emphasized; right arm and leg fully visible, left side partially visible",
	},
	"north-east": {
		view:       "three-quarter back-right view",
		camera:     "camera behind and to the right, rotated about 45 degrees",
		body:       "the character is turned away from the viewer, showing the back-right side",
		visibility: "face hidden except a hint of the right jaw; back and right shoulder prominent, right arm and leg visible from behind",
	},
}

// FacingPromptSection builds the direction-lock instruction to insert into the strip prompt.
// Returns an empty string for an unknown direction.
func FacingPromptSection(key string) string {
	d, ok := facingDescs[key]
	if !ok {
		return ""
	}
	return "Facing direction lock (overrides any other facing or view instruction in this prompt):\n" +
		"- Required view: " + d.view + " — " + d.camera + ".\n" +
		"- Body orientation: " + d.body + ".\n" +
		"- Visibility: " + d.visibility + ".\n" +
		"- The attached reference image shows this character from the front; redraw the IDENTICAL character (same hair, outfit, colors, proportions) rotated to this view.\n" +
		"- Every frame in the strip must use this exact same viewing angle. Never drift back toward a front view and never mirror the character between frames.\n"
}

// MirrorNRGBA returns a new horizontally-flipped copy of the image (used to generate the 8-direction mirror pairs).
func MirrorNRGBA(src *image.NRGBA) *image.NRGBA {
	b := src.Bounds()
	w, h := b.Dx(), b.Dy()
	dst := image.NewNRGBA(image.Rect(0, 0, w, h))
	for y := 0; y < h; y++ {
		srcRow := src.PixOffset(b.Min.X, b.Min.Y+y)
		dstRow := dst.PixOffset(0, y)
		for x := 0; x < w; x++ {
			s := srcRow + x*4
			d := dstRow + (w-1-x)*4
			copy(dst.Pix[d:d+4], src.Pix[s:s+4])
		}
	}
	return dst
}
